services:
  reservations:
    build:
      context: .
      dockerfile: ./app/reservations/Dockerfile
      target: development
    command: pnpm start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  #mongo
  ##image: mongo
